# Generated by Django 3.1.2 on 2021-12-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter street and number of university building', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_floor', models.PositiveSmallIntegerField(default=1, help_text='Enter the university floor (from 1 to 9)')),
                ('building', models.ForeignKey(help_text='select in which building this floor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.building')),
            ],
        ),
    ]
