# Generated by Django 3.1.2 on 2021-12-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_graphic_card_hdd_pc_proc_ram_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='proc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.proc'),
        ),
    ]
