# Generated by Django 3.1.2 on 2021-12-15 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_pc_proc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='number_of_floor',
            field=models.IntegerField(default=1, help_text='Enter the university floor (from 1 to 9)'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='pc',
            field=models.UUIDField(default=uuid.uuid4, help_text='Inventory ID for PC', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pc',
            name='proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.proc'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='processor',
            field=models.CharField(choices=[('1', 'AMD Ryzen 5000'), ('2', 'Intel i5 12600'), ('3', ' AMD Ryzen 9 5900X'), ('4', ' Intel i3 9100')], default='2', max_length=1),
        ),
    ]
