# Generated by Django 3.1.2 on 2021-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20211215_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proc',
            name='processor',
        ),
        migrations.AddField(
            model_name='proc',
            name='anime',
            field=models.CharField(choices=[('1', 'Amd Ryzen 5000'), ('2', 'Intel I5 12600'), ('3', 'Amd Ryzen 9 5900X'), ('4', 'Inte I3 9100')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
