# Generated by Django 3.1.2 on 2021-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20211215_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proc',
            name='anime',
        ),
        migrations.AddField(
            model_name='proc',
            name='processor',
            field=models.CharField(choices=[('AMD_Ryzen_5000', 'Ryzen 5000')], max_length=70, null=True),
        ),
    ]
