# Generated by Django 4.0 on 2021-12-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_remove_pc_proc_pc_processor_alter_proc_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(help_text='select in which building this floor', null=True, on_delete=django.db.models.deletion.CASCADE, to='table.building'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number_of_floor',
            field=models.IntegerField(help_text='Enter the university floor'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='processor',
            field=models.CharField(choices=[('AMD_Ryzen_5000', 'Amd Ryzen 5000'), ('Intel_i5_12600', 'Intel I5 12600'), ('AMD_Ryzen_9_5900', 'Amd Ryzen 9 5900X'), ('Intel_i3_9100', 'Intel I3 9100')], max_length=70, null=True),
        ),
    ]
