# Generated by Django 4.0 on 2021-12-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_rename_place_workplace_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Workplace', 'verbose_name_plural': 'Worplaces'},
        ),
        migrations.AddField(
            model_name='pc',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.workplace'),
        ),
    ]
