# Generated by Django 4.0 on 2021-12-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplace',
            old_name='places',
            new_name='place',
        ),
    ]
