# Generated by Django 4.0 on 2021-12-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_rename_places_workplace_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proc',
            name='id_proc',
        ),
        migrations.RemoveField(
            model_name='proc',
            name='processor',
        ),
        migrations.AddField(
            model_name='pc',
            name='videocard',
            field=models.CharField(choices=[('ASUS_Geforce_GTX_1050_Ti', 'Asus Geforce Gtx 1050 Ti'), ('HP_Radeon_HD_7670', 'Hp Radeon Hd 7670'), ('AMD_Radeon_HD8490', 'Amd Radeon Hd8490'), ('ASUS GeForce GT 710', 'Asus Geforce Gt 710')], max_length=50, null=True),
        ),
    ]
