# Generated by Django 4.0 on 2021-12-16 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_delete_proc_pc_hdd_pc_memmory_alter_pc_processor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graphic_card',
        ),
        migrations.DeleteModel(
            name='HDD',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Workplace', 'verbose_name_plural': 'Worklaces'},
        ),
        migrations.AddField(
            model_name='pc',
            name='hdd_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Inventory ID of this hdd'),
        ),
        migrations.AddField(
            model_name='pc',
            name='memmory_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Inventory ID of this memmory'),
        ),
        migrations.AddField(
            model_name='pc',
            name='processor_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Inventory ID of this proc'),
        ),
        migrations.AddField(
            model_name='pc',
            name='videocard_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Inventory ID of this videocard'),
        ),
    ]
