# Generated by Django 4.0 on 2021-12-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0016_delete_graphic_card_delete_hdd_delete_ram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'Workplace', 'verbose_name_plural': 'Workplaces'},
        ),
        migrations.RenameField(
            model_name='pc',
            old_name='time_of_setup',
            new_name='date_of_setup',
        ),
        migrations.AlterField(
            model_name='pc',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.workplace'),
        ),
    ]
